# Generated by Django 5.0.3 on 2024-03-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_remove_customuser_about_remove_customuser_calendar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='stage',
            field=models.CharField(choices=[('new', 'New'), ('qualifying', 'Qualifying'), ('proposal', 'Proposal'), ('negotiating', 'Negotiating'), ('archive', 'Archive')], default='new', max_length=50),
        ),
    ]
