# Generated by Django 5.0.3 on 2024-03-24 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_lead_stage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='stage',
            new_name='status',
        ),
    ]
